apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: ip-webapp
spec: 
  selector: 
    matchLabels: 
      app: ip-webapp 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: ip-webapp 
    spec: 
      containers: 
      - name: ip-webapp 
        image: cloud.canister.io:5000/nltimv/ip-webapp:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: ip-webapp
spec: 
  selector: 
    app: ip-webapp 
  ports: 
  - protocol: TCP 
    port: 80 