apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: ip-webapp
spec: 
  selector: 
    matchLabels: 
      app: ip-webapp 
  replicas: 10
  template:
    metadata: 
      labels: 
        app: ip-webapp 
    spec: 
      containers: 
      - name: ip-webapp 
        image: registry.gitlab.com/nltimv/notifierapp-repo/testservice:#{Build.BuildId}#
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: gitlab-creds #https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
---  
kind: Service 
apiVersion: v1 
metadata: 
  name: ip-webapp
spec: 
  selector: 
    app: ip-webapp 
  ports: 
  - protocol: TCP 
    port: 80 